# Generated by Django 4.1.3 on 2022-12-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codigo',
        ),
    ]
