# Generated by Django 4.1.3 on 2022-12-04 14:36

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=65)),
                ('ingredientes', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pago', models.BooleanField(blank=True)),
                ('nomeDoCliente', models.CharField(max_length=65)),
                ('telefone', models.CharField(max_length=35)),
                ('endereco', models.CharField(max_length=255)),
                ('hora', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Criado'), (2, 'Cozinha'), (3, 'Efetuado'), (4, 'Entrega'), (5, 'Entregue')], default=app.models.Status['Criado'])),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('entrega', models.BooleanField(blank=True)),
                ('metodoPagamento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='app.metodospagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=1, default=1, max_digits=8)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.produto')),
            ],
        ),
    ]
