# Generated by Django 4.1.3 on 2022-11-22 01:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=35)),
                ('nome', models.CharField(max_length=65)),
                ('ingredientes', models.TextField()),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=35)),
                ('pago', models.BooleanField()),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nomeCliente', models.CharField(max_length=65)),
                ('telefone', models.CharField(max_length=35)),
                ('endereco', models.CharField(max_length=255)),
                ('horarioPedido', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Criado'), (2, 'Efetuado'), (3, 'Entregue')], max_length=35)),
                ('observacao', models.TextField()),
                ('entrega', models.BooleanField()),
                ('metodoPagamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.metodospagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=35)),
                ('quantidade', models.DecimalField(decimal_places=1, max_digits=8)),
                ('observacao', models.TextField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.produto')),
            ],
        ),
    ]
