# Generated by Django 4.1.3 on 2022-11-23 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_itempedido_id_alter_metodospagamento_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='valorTotal',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data.pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data.produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodoPagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='data.metodospagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nomeCliente',
            field=models.CharField(max_length=65, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(1, 'Criado'), (2, 'Efetuado'), (3, 'Entregue')]),
        ),
    ]
