# Generated by Django 4.1.3 on 2022-11-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_pedido_valortotal_alter_itempedido_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='status',
            new_name='statusPedido',
        ),
    ]
