# Generated by Django 4.1.3 on 2022-11-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_status_pedido_statuspedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='statusPedido',
            new_name='status',
        ),
    ]
