# Generated by Django 4.1.3 on 2022-11-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename_nomecliente_pedido_nomedocliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='codigo',
            field=models.CharField(blank=True, default='5c01f6eb-0ae9-47cf-b6cd-0f10b7129fa8', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, default='d6908a9a-f40a-4b5b-8c6a-08c7cb4652af', max_length=40),
        ),
    ]
