# Generated by Django 4.1.3 on 2022-11-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_itempedido_codigo_alter_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='codigo',
            field=models.CharField(blank=True, default='6a1d1973-46e6-48c3-952c-e348b9c452e9', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, default='27af3ce9-acaa-4fdf-be80-32cad499de08', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nomeDoCliente',
            field=models.CharField(max_length=65),
        ),
    ]
