# Generated by Django 4.1.3 on 2022-11-25 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_itempedido_codigo_alter_pedido_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='codigo',
            field=models.CharField(blank=True, default='ac3787df-1c2c-4a87-bfc3-cee182b4139c', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, default='4bfa9b79-5572-47d7-8978-be3c5f32f665', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodoPagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='data.metodospagamento'),
        ),
    ]
