# Generated by Django 4.1.3 on 2022-11-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_itempedido_codigo_alter_pedido_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='codigo',
            field=models.CharField(blank=True, default='2705132c-2d3a-4135-832d-3894e88e45b1', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, default='33e242ed-b8cb-420c-a16a-ee61b8498947', max_length=40),
        ),
    ]
