# Generated by Django 4.1.3 on 2022-11-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_itempedido_codigo_alter_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='codigo',
            field=models.CharField(blank=True, default='26506cb3-8a3d-4462-bca8-6429ae935894', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, default='7637ab1d-65b0-4fd3-a565-2393555419ee', max_length=40),
        ),
    ]
