# Generated by Django 4.1.3 on 2022-11-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_itempedido_codigo_alter_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='codigo',
            field=models.CharField(blank=True, default='311ffc9b-7358-46fa-8e68-fcefa5440cb5', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, default='b1f07ac1-600c-448b-8824-bfccd62b70bc', max_length=40),
        ),
    ]
