# Generated by Django 4.1.3 on 2022-11-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_itempedido_codigo_alter_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='codigo',
            field=models.CharField(blank=True, default='6c1aa195-b807-41f6-8055-f0dbe6c9b7be', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, default='6edb1071-1d98-43b3-a45d-b115e0596ba7', max_length=40),
        ),
    ]
