# Generated by Django 4.1.3 on 2022-11-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_itempedido_codigo_alter_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='codigo',
            field=models.CharField(blank=True, default='d84bbe52-5518-444f-ac0c-a3691b2b505d', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, default='a5ebe835-eb25-4898-a902-07b72891a4f2', max_length=40),
        ),
    ]
