# Generated by Django 4.1.3 on 2022-11-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_itempedido_codigo_alter_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='codigo',
            field=models.CharField(blank=True, default='33bcd3c3-ad3a-4a9a-b5ac-bb6e6e519a0b', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, default='a22b50ce-7b90-442f-bd25-61748d813b9d', max_length=40),
        ),
    ]
