# Generated by Django 4.1.3 on 2022-11-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_itempedido_codigo_alter_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='codigo',
            field=models.CharField(blank=True, default='9293891d-f4d2-442d-a554-9b162090d908', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, default='b70d504d-5186-45ef-a24a-92928b8d9ba6', max_length=40),
        ),
    ]
