# Generated by Django 4.1.3 on 2022-11-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_itempedido_codigo_alter_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='codigo',
            field=models.CharField(blank=True, default='bacb853b-f8a9-459c-81a6-29a0dd4ffeb1', max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, default='9fb95683-b3ce-4270-a874-73411e85d288', max_length=40),
        ),
    ]
